server:
  port: 8080
spring:
  application:
    name: car-listing
  datasource:
    url: jdbc:postgresql://postgres:5432/car_listing
    username: db
    password: db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
